---
title: "Tracker  for field data collection"
author: "Amos Nyarwaya"
date: "5/20/2022"
output: 
   html_document:
     toc: true
     toc_float:
       collapsed: false
       smooth_scroll: false
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(dirname(inputFile), '/field_data_collection_tracker_', format(Sys.Date(), '%Y_%m_%d'),'.html')) })       
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)
# read packages
library(tidyverse)
library(lubridate)
library(glue)
library(leaflet)

# read data
df_settlement_samples_required_an <- readxl::read_excel("../inputs/samples_settlement_definition.xlsx") %>% 
  mutate(settlement_name = str_replace(string = settlement_name, pattern = "_ii$", replacement = "_II"),
         settlement_name = ifelse(settlement_name == "adjumani", str_to_lower(Name_Zn), settlement_name),
         settlement_name= case_when(settlement_name == "alere" ~ "alere ii",
                                    settlement_name == "ayilo ii" ~ "ayiloii",
                                    settlement_name == "mirieyi" ~ "mireyi",
                                    settlement_name == "mungula 2" ~ "mungula ii",
                                    settlement_name == "pagirinya" ~ "pagrinya",
                                    TRUE ~ settlement_name)) %>% 
  select(settlement_name, smpl_sz)

df_host_samples_required_an <- readxl::read_excel("../inputs/samples_host_sub_definition.xlsx")%>% 
  select(sub_county_name, smpl_sz)

df_tool_data_an <- readxl::read_excel("../inputs/UGA2103_Financial_Service_Providers_Assessment_HH_Tool_June2021.xlsx") %>% 
  mutate(uuid = `_uuid`,
         start_date = as_date(start),
         start = as_datetime(start),
         end = as_datetime(end),
         latitude = as.numeric(`_geopoint_latitude`),
         longitude = as.numeric(`_geopoint_longitude`)) %>% 
  filter(consent == "yes", 
         start_date > as_date("2021-08-29"), 
         point_number != "13m.", 
         !start_date %in% c(as_date("2021-09-08"), as_date("2021-09-09"), 
                            as_date("2021-09-21")),
         !str_detect(string = point_number, pattern = fixed('test', ignore_case = TRUE)),
         !uuid %in% c("27b0ffe2-8d47-4897-b402-1928fd23cfb3",
                      "40d216de-76db-42b7-9105-aea1ce234489",
                      "f2f648df-55d6-4b9d-93ca-aa87c3bc30c7",
                      "4167b891-b1ff-46b1-856b-532dd28e7a1e",
                      "d7bde578-cdc2-4d77-b31b-a15c4cec9d38",
                      "4f3afa4f-a065-4f6d-bd25-9919902f9ce0",
                      "a89d0010-d626-4a4f-8b8c-e83e8fade349",
                      "27ac9f75-3954-4c55-90a3-b5b09984fe7a",
                      "48ee8073-a0d7-460f-9867-304a47bdb1fc",
                      "b0a1c83dcdb24671b9eed78d7a77786f",
                      "c5c9b13aa6cd43338e113d8c647c04ed",
                      "d8936d35-7e1c-48d9-bafa-b25e758c05eb"
         ))

# days that contain data
df_days_for_data_collection_an <- df_tool_data_an %>% select(start_date) %>% unique() %>% arrange(start_date) %>% pull()

df_data_support_cl_log <- df_tool_data_an %>% 
  select(uuid, status,sub_county_name,	settlement_name, latitude,	longitude )

# cleaning log handling
df_cl_log <- read_csv(file = "../inputs/combined_logic_spatial_and_others_checks.csv") %>% 
  mutate(adjust_log = ifelse(is.na(adjust_log), "apply_suggested_change", adjust_log)) %>% 
  left_join(df_data_support_cl_log, by = "uuid")

# change_response logs that affect stats in the data collection progress
cl_log_change_response <- df_cl_log %>% 
  filter(type == "change_response", 
         !is.na(value),
         reviewed == 1, 
         adjust_log != "delete_log", 
         !issue_id %in% c("other_checks", "logic_c_main_language",  "logic_c_internet_awareness") ) %>% 
  select(uuid, name, value)

# updated tool data
df_updated_tool_data_an <- df_tool_data_an

# get uuids from cleaning log
uuids_chg_response_an <- cl_log_change_response %>% pull(uuid) %>% unique()

for (current_uuid in uuids_chg_response_an) {
  current_uuid_data <- cl_log_change_response %>% 
    filter(uuid == current_uuid) %>% 
    mutate(value = ifelse(name == "enumerator_id", as.numeric(value), value)) %>% 
    pivot_wider(names_from = "name", values_from = "value", uuid)
  print(current_uuid_data)
  
  # process current updates
  df_current_updated_an <- df_updated_tool_data_an %>% 
    rows_update(y = current_uuid_data, by = "uuid")
  
  # update the parent dataset with current updates
  df_updated_tool_data_an <- df_current_updated_an
}

# enumerator performance data
df_enum_performance_an <- df_updated_tool_data_an %>% 
  mutate(int.survey_time_interval = lubridate::time_length(end - start, unit = "min"),
         int.survey_time_interval = ceiling(int.survey_time_interval)) 

```


```{r, echo = FALSE}

```


